# JVM Memory Settings
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=/home/sergsavaryn/.local/share/PrismLauncher/java/java-runtime-delta
org.gradle.configuration-cache=false

# Mod Metadata
mod_version=2.1.0
maven_group=com.syntren.sypass
archives_name=sypass
enabled_platforms=fabric,neoforge

# Target Environment
minecraft_version=1.21.1

# Toolchain Versions
architectury_loom_version=1.9-SNAPSHOT
architectury_plugin_version=3.4-SNAPSHOT
shadow_version=8.3.6

# Fabric Dependencies
fabric_loader_version=0.16.10
fabric_api_version=0.116.15+1.21.1
modmenu_version=11.0.3

# NeoForge Dependencies
neoforge_version=21.1.172
